// <auto-generated />
namespace Nwind.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ugur11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ugur11));
        
        string IMigrationMetadata.Id
        {
            get { return "202504271634324_ugur11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
